server:
  port: 80
  servlet:
    context-path: /deploy

spring:
  profiles: default
  freemarker:
    template-loader-path: classpath:/webapp/WEB-INF/ftl/
    cache: true
    check-template-location: true
    content-type: text/html; charset=UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

jboss:
  deploys:
    dir: /home/jbossuser/wildfly-servlet-10.1.0.Final/standalone/deployments/
  logs:
    dir: /home/jbossuser/wildfly-servlet-10.1.0.Final/standalone/log/
    
logging:
  config: classpath:logback-spring.xml
